wb-gen-serial: look into dt /wirenboard/serial-number
wirenboard/wb-utils pull request #109
Opened 2023-07-27 13:07 UTC by vdromanov

По умолчанию смотрим в /wirenboard/serial-number на предмет серийника

2023-07-27 14:51 UTC, sikmir commented on utils/bin/wb-gen-serial
> +    path = "/proc/device-tree/wirenboard/serial-number"
Сейчас в dt нет `/wirenboard/serial-number`, он там появится в будущем?

2023-07-28 07:34 UTC, vdromanov commented on utils/bin/wb-gen-serial
> +    path = "/proc/device-tree/wirenboard/serial-number"
в этом и вся задумка

2023-07-28 07:38 UTC, sikmir approved these changes

2023-07-28 07:44 UTC, vdromanov commented
@sikmir в заморозку сейчас - не надо!

2023-07-31 10:43 UTC, webconn requested changes
На обсуждении с Женей решили, что это порочная практика, и надо как минимум ноду переименовать для совместимости со старыми кастомными серийниками, а вообще скорее брать данные по умолчанию из `/serial-number`

2023-08-01 12:19 UTC, vdromanov commented
сделал, как обсуждали с @evgeny-boger 
смотрим в :
/proc/device-tree/serial-number => wirenboard/device-serial => генерируем серийник

2023-08-02 11:15 UTC, webconn commented on utils/bin/wb-gen-serial
> +            return f.read().strip().removesuffix("\x00")
А чем это лучше, чем было? По-моему наоборот получилось, твой код может оставить пробелы в конце строки (потому что строка будет вида `abcd   \0`)

2023-08-02 11:15 UTC, webconn commented on utils/bin/wb-gen-serial
> +        int(sn, 16)
Тут бы дописать, что это ради выброса исключения, а то глаз спотыкается. Ну или сделать проверку через `string.hexdigits`, как на том же SO предлагают

2023-08-02 11:15 UTC, webconn commented on utils/bin/wb-gen-serial
> +        sn = default_sn_path.read_text().strip().removesuffix("\x00")
Аналогично комменту выше, тут как будто немного неправильно всё делается

2023-08-02 11:15 UTC, webconn commented on utils/bin/wb-gen-serial
> +        print(get_serial())
Давай тогда ещё в `parser` параметр `version` пометим как deprecated в help

2023-08-02 15:50 UTC, vdromanov commented on utils/bin/wb-gen-serial
> +            return f.read().strip().removesuffix("\x00")
подумали - правда лучше старый подход с rstrip использовать

вернул

2023-08-02 15:50 UTC, vdromanov commented on utils/bin/wb-gen-serial
> +        int(sn, 16)
готово (дописал коммент)
вариант с SO мне не нравится, т.к. длиннее, тянет импорт, медленнее

2023-08-02 15:50 UTC, vdromanov commented on utils/bin/wb-gen-serial
> +        sn = default_sn_path.read_text().strip().removesuffix("\x00")
готово

2023-08-02 15:50 UTC, vdromanov commented on utils/bin/wb-gen-serial
> +        print(get_serial())
готово

2023-08-03 11:25 UTC, webconn commented on utils/bin/wb-gen-serial
> +        int(sn, 16)  # check, is a hexadecimal number
```suggestion
        int(sn, 16)  # throws ValueError if string is not a hex number

2023-08-03 11:33 UTC, webconn approved these changes

2023-08-03 15:56 UTC, merged