WBEC support
wirenboard/wb-utils pull request #115
Opened 2023-08-09 15:40 UTC by webconn

До полноценного PR надо влить https://github.com/wirenboard/linux/pull/143 и https://github.com/wirenboard/wirenboard/pull/160, проверить, что бутлет корректно работает на предыдущих версиях WB7 и на WB7.4, и заменить основной бутлет на S3 на новый.

Этот патч добавляет обновление прошивки WBEC во время factory reset, а также добавляет пару отладочных флагов в скрипт установки FIT: 

-  `--console-log` - пишет весь вывод скрипта обновления в файл `console.log` рядом с FIT-файлом, полезно при удалённой отладке при прошивке через webupd;
- `--custom-postinst` - при добавлении этого флага в момент вызова postinst-скриптов из rootfs будут вызваны так же (и в таком же окружении) скрипты из директории `install_update.postinst` рядом с FIT-файлом. Полезно при отладке postinst-скриптов без пересборки образа.

2023-08-09 15:42 UTC, webconn commented on utils/lib/wb-image-update/fit/build.sh
> +    TARGET=wb74  # FIXME
Это место вернётся обратно после вливания PR вокруг бутлета и выкладывания нового бутлета по умолчанию

2023-08-13 23:50 UTC, evgeny-boger requested changes

2023-08-13 23:50 UTC, evgeny-boger commented on utils/bin/wb-run-update
> +        die "Firmware is not compatible with this device"
хочу лучше сообщение
1) почему именно несовместим? Явно написать про dtb
2) написать что делать - скачать прошивку свежее

2023-08-14 07:14 UTC, webconn commented on utils/bin/wb-run-update
> +        die "Firmware is not compatible with this device"
Дописал

2023-08-14 08:50 UTC, vdromanov commented on utils/lib/wb-image-update/fit/install_update.sh
> +        FINAL_CONSOLE_LOG_FILE="$(dirname "$FIT")/console.log"
мб назвать wb-console.log?
пользователям будет проще гуглить

2023-08-14 08:51 UTC, vdromanov commented on utils/lib/wb-image-update/fit/install_update.sh
> +        FINAL_CONSOLE_LOG_FILE="$(dirname "$FIT")/console.log"
я бы вообще его по умолчанию включил

и в diag-collect собирал бы

много дебага - не мало дебага

2023-08-14 08:55 UTC, webconn commented on utils/lib/wb-image-update/fit/install_update.sh
> +        FINAL_CONSOLE_LOG_FILE="$(dirname "$FIT")/console.log"
> я бы вообще его по умолчанию включил

Может, кстати, и стоит

2023-08-14 12:10 UTC, vdromanov approved these changes

2023-08-18 10:55 UTC, webconn commented
Этот PR понадобилось разбить на два, отдельно про проверку совместимости fit (https://github.com/wirenboard/wb-utils/pull/123) и ещё один непосредственно с поддержкой wbec. Нужно, чтобы заранее собрать бутлет с проверкой совместимости.

2023-08-18 10:55 UTC, closed without merging