Feature/protect factory fit
wirenboard/wb-utils pull request #162
Opened 2024-09-26 22:37 UTC by vdromanov

Вешаем immutable-атрибут на factory-fit. Иногда надо менять factory-fit -> играемся с chattr. 

Всегда восстанавливаем изначальный immutable-state, т.к. для корректной работы c immutable-factory-fit нужен починеный fit-info => иначе, если обновление через apt прилетит на уже выпущенные контроллеры - всё сломается (не смогут прошиться в бутлете)

сейчас какие-то проблемы со сборкой fit-а; чуть позже добавлю на потыкать

2024-10-01 06:58 UTC, webconn requested changes
мне не нравится. всё, что добавляет логику в скрипты, встроенные в фит, в целом потенциально болезненно, а если обратная совместимость ломается, то это совсем плохо становится. в связанном pr в wb-configs дописал, как можно было бы решить

2024-10-03 12:13 UTC, webconn commented on utils/bin/wb-watch-update
> +        if [[ $EVENT_FILE == "wb_use_factory_fit.flag" ]]; then
тут можно тоже в лог записать, что мы флаг получили. алсо, не может ли быть гонки между появлением фита и файла с флагом? если фит прилетит первым, флаги не дойдут

2024-10-03 12:13 UTC, webconn commented on utils/lib/wb-image-update/fit/install_update.sh
> +        [[ -n "$was_immutable" ]] && chattr +i $CURRENT_FACTORY_FIT
этот кусок кода только в этом файле трижды  повторился. сделать функцией может?

2024-10-03 13:41 UTC, vdromanov commented on utils/bin/wb-watch-update
> +        if [[ $EVENT_FILE == "wb_use_factory_fit.flag" ]]; then
про гонку - обсудили; у нас загрузка fit-а происходит из другого cgi-скрипта, в котором нет логики с флагом

лог - готово

2024-10-03 13:41 UTC, vdromanov commented on utils/lib/wb-image-update/fit/install_update.sh
> +        [[ -n "$was_immutable" ]] && chattr +i $CURRENT_FACTORY_FIT
в этом файле - получилось функцией

в остальных - по одному разу => смысла нет; подтягивать из внешнего файла - тоже такое себе => предлагаю забить

2024-10-04 10:15 UTC, webconn approved these changes
на железе не тестил

2024-10-07 21:19 UTC, merged