Feature/sim7000e fix
wirenboard/wb-utils pull request #19
Opened 2019-05-17 16:36 UTC by vdromanov

Проблема: в контроллерах с NB-IOT модемом генерируется неправильный серийник (без учёта imei модема).
Причина: в sim7000e автоопределение BD. У нас прописано посылать в порт "AAAAAAAAAT" для определения BD, но с sim7000e это не работает. Нужно несколько раз послать "AT".
Решение: смотрим в оверлеи: если есть sim7000e - шлём 10 раз "AT\r\n"; если нет - всё, как раньше.
Проверил на sim800 с оверлеями/без; на sim5300e с оверлеями/без; на sim7000e

2019-05-20 12:12 UTC, evgeny-boger requested changes

2019-05-20 12:12 UTC, evgeny-boger commented on gsm/wb-gsm-common.sh
> +    synchronize_bd
bd => baudrate

2019-05-20 12:12 UTC, evgeny-boger commented on gsm/wb-gsm-common.sh
> +function is_7000e() {
соседние функции называются не так: `is_neoway_m660a`
надо так же, добавить производителя.

2019-05-20 12:12 UTC, evgeny-boger commented on gsm/wb-gsm-common.sh
> +    ret="grep -i $SEARCH_PATTERN $OVERLAY_FNAME"
что тут будет, если оверлеев нет? Это нужно проверить на контроллере без оверлеев.

Мы можем считать, что во всех моделях с SIM7000E оверлеи есть, главное чтобы этот код не вываливался на более старых контроллерах.

2019-05-20 12:12 UTC, evgeny-boger commented on gsm/wb-gsm-common.sh
> +    ret="grep -i $SEARCH_PATTERN $OVERLAY_FNAME"
в целом это выглядит как какой-то гигантский костыль. Надо смотреть в конкретный property конкретной нужной ноды, а не грепать всё дерево. на строчку. 

У нас в wb-utils же есть даже тулзы для этого.

2019-05-21 14:38 UTC, vdromanov commented on gsm/wb-gsm-common.sh
> +    synchronize_bd
fixed

2019-05-21 14:38 UTC, vdromanov commented on gsm/wb-gsm-common.sh
> +function is_7000e() {
fixed

2019-05-21 14:38 UTC, vdromanov commented on gsm/wb-gsm-common.sh
> +    ret="grep -i $SEARCH_PATTERN $OVERLAY_FNAME"
Сразу проверял на WB5 с sim800 и на WB5 с sim5300e, не вываливался. Переделал под тулзы; проверил на тех же WB - не вываливается.

2019-05-21 14:38 UTC, vdromanov commented on gsm/wb-gsm-common.sh
> +    ret="grep -i $SEARCH_PATTERN $OVERLAY_FNAME"
так и сделал. Про тулзы не знал - оказались удобными!

2019-05-31 08:29 UTC, merged