Feature/wb67
wirenboard/wb-utils pull request #20
Opened 2020-08-24 14:16 UTC by vdromanov

В wb6.7 генерация серийника отвязана от imei модема. Если dts compatible с contactless,imx6ul-wirenboard670 - не смотрим в imei.

Погонял на 6.6 и 6.7

2020-08-24 21:11 UTC, evgeny-boger requested changes

2020-08-24 21:11 UTC, evgeny-boger commented on board/wb-gen-serial
> +        return True if compatible_str in compatible_with else False
return (compatible_str in compatible_with)

2020-08-24 21:11 UTC, evgeny-boger commented on board/wb-gen-serial
> +    except IOError:
а для чего это здесь? На наших платах /proc/device-tree/compatible всегда есть. 
Ну и вообще игнорировать ошибки - это плохо.

2020-08-24 21:11 UTC, evgeny-boger commented on board/wb-gen-serial
> +        try:
а раньше оно тут как работало? Опять молчаливая обработка на общую RuntimeError - верный способ словить сложно отлаживаемый баг.

Вообще serial v.1 нигде уже сто лет не используется, думаю особо и поддерживать не надо.

2020-08-24 21:11 UTC, evgeny-boger commented on debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, lsb-base (>= 4.1), u-boot-tools-wb (>= 2015.07+wb-3), inotify-tools, pv, jq, nginx-extras, python-wb-common (>= 1.3.2), wb-configs (>= 1.69.4), linux-imag
оно не зависит от ядра на самом деле

2020-08-25 07:37 UTC, vdromanov commented on board/wb-gen-serial
> +        try:
Также и работало. [gsm](https://github.com/wirenboard/wb-common/blob/master/wb_common/gsm.py) - это subprocess-обёртки вокруг wb-gsm, которые кидают RuntimeError в случае неудачной работы с модемом.

я бы как-то развил питонский gsm: свои ошибки, логгирование, AT-команды из тест-сьюта, управление sim-картами, ...

2020-08-25 07:44 UTC, vdromanov commented on debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, lsb-base (>= 4.1), u-boot-tools-wb (>= 2015.07+wb-3), inotify-tools, pv, jq, nginx-extras, python-wb-common (>= 1.3.2), wb-configs (>= 1.69.4), linux-imag
вот тут не понял. compatible-строчка разве не в dts ядра прописана?

которую мы говорим загружать в `factory-fdt` ноды wirenboard в начале флешки

2020-08-25 07:46 UTC, vdromanov commented on board/wb-gen-serial
> +        return True if compatible_str in compatible_with else False
готово

2020-08-25 07:46 UTC, vdromanov commented on board/wb-gen-serial
> +    except IOError:
не посмотрел про все платы. убрал try/except

2020-08-25 08:33 UTC, evgeny-boger commented on debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, lsb-base (>= 4.1), u-boot-tools-wb (>= 2015.07+wb-3), inotify-tools, pv, jq, nginx-extras, python-wb-common (>= 1.3.2), wb-configs (>= 1.69.4), linux-imag
wb6.7 со старым ядром же будет, а на других контролерах нам неважно, есть ли 6.7 в dts. Думаю, что всё-таки лучше убрать - меньше обновлений другим клиентам.

2020-08-25 08:34 UTC, evgeny-boger commented on board/wb-gen-serial
> +        try:
раньше в этом месте try не было, я про это.

Развивать там не очень понятно как, я бы от пользователей начинал. Возможно будет ModemManager, возможно что-то своё питоновское. Господа из Гейзера вот свой скрипт на питоне делали, нам отдали.

2020-08-25 09:51 UTC, vdromanov commented on debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, lsb-base (>= 4.1), u-boot-tools-wb (>= 2015.07+wb-3), inotify-tools, pv, jq, nginx-extras, python-wb-common (>= 1.3.2), wb-configs (>= 1.69.4), linux-imag
вернул, как было

2020-08-25 09:57 UTC, vdromanov commented on board/wb-gen-serial
> +        try:
там просто старый try/except переехал в else...

2020-08-26 12:55 UTC, merged