Feature/41804 modem no uart
wirenboard/wb-utils pull request #37
Opened 2022-02-04 06:56 UTC by vdromanov

Поддержка USB-онли модемов (т.к. в wb7 нет uart для этого). UART+usb модемы ведут себя, как раньше

Основная идея - знаем, что модем висит на своём отдельном USB и смотрим, какие устройства на нем появляются. Погонял - работают: a7600e, sim5300e, quectel ec200t. По идее, все будет работать

адрес usb предлагаю брать из device-tree (там захардкодил)

2022-02-04 13:08 UTC, webconn requested changes

2022-02-04 13:08 UTC, webconn commented on debian/changelog
> +wb-utils (3.4.2) stable; urgency=medium
3.5.0

2022-02-04 13:08 UTC, webconn commented on utils/lib/wb-gsm-common.sh
> +        RC=$(test_connection $PORT 5)
timeout можно отсюда убрать, если он везде одинаковый и снаружи не задаётся

2022-02-04 13:08 UTC, webconn commented on utils/lib/wb-gsm-common.sh
> +    echo $(readlink -f /dev/serial/by-path/platform-$(of_get_prop_str "wirenboard/gsm" "usb-soc-addr")*);
Мне не нравится такое решение, если честно. Более естественным кажется отбирать устройство по паре vid:pid каким-то образом. Это всё можно нехило упростить с помощью udev: написать правило, которое для конкретных пар vid:pid будет создавать алиас вида `/dev/ttyGSM`. Возможно, и сюда после этого особых изменений не понадобится, да и из ядра можно было бы убрать.

@evgeny-boger что скажешь?

2022-02-04 13:17 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    echo $(readlink -f /dev/serial/by-path/platform-$(of_get_prop_str "wirenboard/gsm" "usb-soc-addr")*);
ну да, как-то неконсистентно. Ладно бы была привязка к конкретному порту хаба, а так как-то ни туда, ни сюда.

Идеально, думаю, было бы привязать именно к физическому адресу, но с точностью до порта. Если не получится или сложно, то уже думать.

Проблема с vid/pid в том, что они во-первых нестабильные (никто их в даташите не гарантировал), а во-вторых может совпасть с внешним модемом, вставленным в USB.

2022-02-04 13:20 UTC, webconn commented on utils/lib/wb-gsm-common.sh
> +    echo $(readlink -f /dev/serial/by-path/platform-$(of_get_prop_str "wirenboard/gsm" "usb-soc-addr")*);
Технически привязать к расположению можно было бы, кстати

2022-02-04 13:26 UTC, webconn commented on utils/lib/wb-gsm-common.sh
> +    echo $(readlink -f /dev/serial/by-path/platform-$(of_get_prop_str "wirenboard/gsm" "usb-soc-addr")*);
Подключил к wb7 FT232:

```
root@wirenboard-A*******:~# lsusb -t
/:  Bus 06.Port 1: Dev 1, Class=root_hub, Driver=ohci-platform/1p, 12M
/:  Bus 05.Port 1: Dev 1, Class=root_hub, Driver=ohci-platform/1p, 12M
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=ohci-platform/1p, 12M
    |__ Port 1: Dev 8, If 0, Class=Vendor Specific Class, Driver=ftdi_sio, 12M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=ehci-platform/1p, 480M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=ehci-platform/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Wireless, Driver=btusb, 480M
    |__ Port 1: Dev 2, If 1, Class=Wireless, Driver=btusb, 480M
    |__ Port 1: Dev 2, If 2, Class=Vendor Specific Class, Driver=rtl8723bu, 480M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-platform/1p, 480M
root@wirenboard-A*******:~# ls /sys/bus/usb/devices/4-1\:1.0/ -lah
total 0
drwxr-xr-x 6 root root    0 Feb  4 13:21 .
drwxr-xr-x 5 root root    0 Feb  4 13:21 ..
-rw-r--r-- 1 root root 4.0K Feb  4 13:22 authorized
-r--r--r-- 1 root root 4.0K Feb  4 13:22 bAlternateSetting
-r--r--r-- 1 root root 4.0K Feb  4 13:21 bInterfaceClass
-r--r--r-- 1 root root 4.0K Feb  4 13:21 bInterfaceNumber
-r--r--r-- 1 root root 4.0K Feb  4 13:22 bInterfaceProtocol
-r--r--r-- 1 root root 4.0K Feb  4 13:22 bInterfaceSubClass
-r--r--r-- 1 root root 4.0K Feb  4 13:22 bNumEndpoints
lrwxrwxrwx 1 root root    0 Feb  4 13:21 driver -> ../../../../../../../bus/usb/drivers/ftdi_sio
drwxr-xr-x 3 root root    0 Feb  4 13:22 ep_02
drwxr-xr-x 3 root root    0 Feb  4 13:22 ep_81
-r--r--r-- 1 root root 4.0K Feb  4 13:22 interface
-r--r--r-- 1 root root 4.0K Feb  4 13:22 modalias
drwxr-xr-x 2 root root    0 Feb  4 13:22 power
lrwxrwxrwx 1 root root    0 Feb  4 13:21 subsystem -> ../../../../../../../bus/usb
-r--r--r-- 1 root root 4.0K Feb  4 13:22 supports_autosuspend
drwxr-xr-x 4 root root    0 Feb  4 13:21 ttyUSB0
-rw-r--r-- 1 root root 4.0K Feb  4 13:21 uevent
```

2022-02-04 13:30 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    echo $(readlink -f /dev/serial/by-path/platform-$(of_get_prop_str "wirenboard/gsm" "usb-soc-addr")*);
там вроде в линуксе можно на это какое-то даже DT делать, чтобы матчить устройства по vid/pid/и ниже, а для хабов матчить порты:

![image](https://user-images.githubusercontent.com/1755320/152537028-feefe89d-4ca1-4923-85b2-a68b48cf5418.png)

Так можно объявить структуру прямо в DT, а потом уже в sysfs в ней появится ссылка на tty сама.

Вот тут документация: Documentation/devicetree/bindings/usb/usb-device.yaml

2022-02-04 13:39 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +    echo $(readlink -f /dev/serial/by-path/platform-$(of_get_prop_str "wirenboard/gsm" "usb-soc-addr")*);
>> Идеально, думаю, было бы привязать именно к физическому адресу, но с точностью до порта. Если не получится или сложно, то уже думать.

или я что-то не понял, или так и сделано (в ноде wirenboard прописан адрес usb-порта для модема)

2022-02-04 13:45 UTC, webconn commented on utils/lib/wb-gsm-common.sh
> +    echo $(readlink -f /dev/serial/by-path/platform-$(of_get_prop_str "wirenboard/gsm" "usb-soc-addr")*);
Вообще похоже на то, для ft232 у меня он выглядит как `/dev/serial/by-path/platform-1c14400.usb-usb-0:1:1.0-port0`. Но если и добавлять что-то в device tree, то лучше это сделать по возможности встроенными средствами

2022-02-04 14:20 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    echo $(readlink -f /dev/serial/by-path/platform-$(of_get_prop_str "wirenboard/gsm" "usb-soc-addr")*);
>типа "4-1:1.0" можно было бы использовать

это динамические циферки, они ни к чему не привязаны

2022-02-04 14:21 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    echo $(readlink -f /dev/serial/by-path/platform-$(of_get_prop_str "wirenboard/gsm" "usb-soc-addr")*);
>или я что-то не понял, или так и сделано (в ноде wirenboard прописан адрес usb-порта для модема)

1) Сделано не через phandle, а через костыль и строчки.
2) Не будет работать на WB6. 

Т.к. на WB6 тоже в модемах USB, то нам проще какой-то универсальный механизм сразу завезти.

2022-02-07 18:21 UTC, vdromanov commented on debian/changelog
> +wb-utils (3.4.2) stable; urgency=medium
готово

2022-02-07 18:23 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +        RC=$(test_connection $PORT 5)
а вот и не везде

у меня в проверке портов он 2с (много гонял - работает стабильно)
а во всех остальных местах он был 5с. Оставил там 5с, чтобы не пробудить какое-нибудь древнее зло

2022-02-07 18:25 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +    echo $(readlink -f /dev/serial/by-path/platform-$(of_get_prop_str "wirenboard/gsm" "usb-soc-addr")*);
идея с device-tree сработала, всё переделал:

- usb-порт для модема жестко привязан (в device-tree)
- работает и с wb6

погонял на wb6 и wb7

2022-02-07 18:29 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +    local usb_root=$(grep -l $compatible_str /sys/bus/usb/devices/*/of_node/compatible | sed 's/of_node\/compatible//')
магия dts: у сматчившегося (по шине/хабу/порту) девайса в of_node лежит наша compatible-строчка

2022-02-08 17:25 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    local usb_root=$(grep -l $compatible_str /sys/bus/usb/devices/*/of_node/compatible | sed 's/of_node\/compatible//')
у нас есть какие-то хелперы на это. grep не очень правильно, потому что он просто ищет подстроку. Ещё и от нулевого байта-  разделителя строк может сломаться.

Надо ожидать, что там со временем будет что-то типа

```
compatible ="simcom,sim7600e-h", "wirenboard,wbc-usb-modem";
```

и матчить нужно будет по наличию одного элемента.

2022-02-08 17:29 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +function get_at_port() {
у 4G-модемов таких портов два, удобно один использовать для AT, другой для ppp. Хоть ppp и легаси, но клиенты используют всё равно.

Предлагаю:
1) Искать все порты
2) Создавать на них какие-то симлинки(?) в /dev/ , чтобы пользователи тоже могли c этим работать

У конкурентов, например, прямо создётся два порта в /dev/ - один для клиентских AT-команд, один для PPP.

2022-02-10 17:58 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +function get_at_port() {
готово
AT-usb порты - /dev/ttyWBC*

2022-02-10 18:02 UTC, vdromanov commented
симлинки теперь у всех модемов с usb (на картинке - 3g модем на wb6)
![2022-02-10_20-51-34](https://user-images.githubusercontent.com/25829054/153468149-f68c30c9-7150-42e3-b0e6-ed58e6fb34ce.png)

есть ли у модема usb wb-gsm понимает из compatible у wirenboard/gsm
у wb (до 6.7) симлинков на usb не будет

2022-02-10 18:03 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +    local usb_root=$(grep -l $compatible_str /sys/bus/usb/devices/*/of_node/compatible | sed 's/of_node\/compatible//')
готово

2022-02-11 06:23 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +function get_at_port() {
что-то мне название не очень нравится, ведь на старых модемах не было никаких WBC.

Может /dev/ttyGSMx ?

2022-02-11 06:23 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +function get_at_port() {
как оно ведёт себя при смене модема или при отключении модема? Порты пропадут, симлинки останутся?

2022-02-11 06:26 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +        [[ $(test_connection $port 2) == 0 ]] && answered_ports+=( $port )
а тут не много 2 секунды?

2022-02-11 07:10 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +        [[ $(test_connection $port 2) == 0 ]] && answered_ports+=( $port )
на wb6 wb-gsm немножко думает, конечно

попробую 1с

2022-02-14 00:33 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    if [[ $(test_connection $PORT 5) == 0 ]] ; then
а почему тут 5, не много?

2022-02-14 07:21 UTC, vdromanov commented
-> как оно ведёт себя при смене модема или при отключении модема? Порты пропадут, симлинки останутся?

- модем выключен, `wb-gsm on`: ходим по юсб-портам, проверяем, что ответило, делаем симлинки
- модем включен, `wb-gsm что-нибудь`: проверяем, ответили ли симлинки на AT; если нет - предыдущий пункт
- `wb-gsm off`: убираем симлинки, если есть

2022-02-14 09:26 UTC, vdromanov commented
> Может /dev/ttyGSMx ?
готово

2022-02-17 16:37 UTC, webconn commented on utils/lib/wb-gsm-common.sh
> +        # UART has present always (even if modem is turned off)
`is always present`, на правах докопаться

2022-02-17 16:37 UTC, webconn commented on utils/lib/wb-gsm-common.sh
> +            done
Для чуть большей осмысленности я б тут тоже добавил `debug` с сообщением в духе `can't detect ports, initializing USB connection`

2022-02-17 16:37 UTC, webconn commented
Вопрос из любопытства: а у нас будет возможность эти симлинки делать через udev? Они как-то на уровне номеров эндпоинтов могут различаться?

2022-02-20 18:27 UTC, evgeny-boger commented
>Вопрос из любопытства: а у нас будет возможность эти симлинки делать через udev? Они как-то на уровне номеров эндпоинтов могут различаться?

они не документированы, а ещё все симкомовские модемы имеют одинаковый vid и pid. Поэтому, кажется, остаётся только их сканировать.

2022-02-20 19:07 UTC, evgeny-boger requested changes

2022-02-20 19:07 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +        ln -sfn $port $symlinked_port && symlinked_ports+=( $symlinked_port ); let pos+=1
думаю, что надо ещё сделать /dev/ttyGSM без цифр, который покаызывает на первый найденный порт.

2022-02-20 19:07 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
>          gpio_set_value $WB_GPIO_GSM_POWER 0
давай сразу будем парсить *-gpios из новой ноды здесь

А код в of_env, заполняющий WB_GSM оставим для совместимости стороннего софта.

2022-02-20 19:07 UTC, evgeny-boger commented on debian/changelog
> +wb-utils (3.5.0) stable; urgency=medium
ещё, думаю, надо зависимости от нового ядра явно прописать.

2022-02-23 20:40 UTC, vdromanov commented
все предложения готовы

всё проверил (wb5,6x,67,7)

2022-02-23 20:48 UTC, evgeny-boger approved these changes
надо отребейзить

2022-02-23 20:49 UTC, evgeny-boger commented on debian/control
> +         linux-image-wb2 (>= 4.9+wb20180808183130) | linux-image-wb6 (>= 5.10.35-wb106~~) | linux-image-wb7 (>= 5.10.35-wb106~~),
это уже будет 108, если сейчас вольём ядро

2022-02-23 21:17 UTC, webconn approved these changes
Я бы там длинные заклинания с призывами GPIO вытащил в функции, но на беглый взгляд там сейчас всё ок

2022-02-24 11:24 UTC, vdromanov commented
влили ребейз; это - закрываем

2022-02-24 11:24 UTC, closed without merging