wb-watch-update: add delay before sending log/status to mqtt
wirenboard/wb-utils pull request #42
Opened 2022-07-05 11:57 UTC by vdromanov

Связянный загрузкой обновления (нжинкс) pr.
Вкратце - wb-watch-update видит файл и шлет лог раньше, чем закончился cgi-скрипт => в прогрессбаре загрузки этого не видно
![2022-07-05_14-52-42](https://user-images.githubusercontent.com/25829054/177321376-c8e518c4-4751-4c6a-b4bc-67bd514cefda.png)

Подробно - в pr'е в wb-configs

по идее, от задержки здесь никому ни жарко, ни холодно. Проверю на вб на стретче, как буду в офисе (завтра)

2022-07-05 14:37 UTC, webconn requested changes
Так, что-то тут совсем нехорошее происходит. Зачем это здесь? По идее, wb-watch-update должен триггериться только на уже полностью загруженный файл, что тут и происходит

2022-07-05 16:05 UTC, vdromanov commented
так он и триггерится, как надо

подозреваю, раньше nginx (было прописано у него в настроечках) слал 200 после загрузки файла сильно быстрее
т.е. загрузка кончилась => 200 от nginx => фронт нарисовал "Ок" => wb-watch-update увидел файлик и написал статус

а сейчас - из-за буферизации cgi мы не можем отдать 200 раньше, чем весь py-скрипт отработает; т.е:
загрузка кончилась => wb-watch-update увидел файлик и написал статус => py-скрипт отработал => 200

=> полезную нам информацию от wb-watch-update не видно

2022-07-06 10:25 UTC, webconn commented
В общем, я за то, чтобы эту часть пока не трогать никак, а вместо этого подправить интерфейс, чтобы он реагировал не только на 200 для переключения в режим просмотра логов, но и на начало логов, например

2022-07-12 15:22 UTC, vdromanov commented
проблему решили на фронте; неактуально

2022-07-12 15:22 UTC, closed without merging