Feature/40722 systemd conditions
wirenboard/wb-utils pull request #44
Opened 2022-07-22 07:49 UTC by vdromanov

- убрали wb-gsm-rtc; вообще-совсем (по задумке, на wb5 пакет заезжать не будет)

- wb-repart стал теперь wb-check-partitions: перестал переразмечать разделы; стал сваливаться в emergency, если с разделами что-то не то

- wb-prepare стал триггериться по systemd-firstboot

2022-07-22 07:57 UTC, webconn commented on debian/wb-utils.wb-prepare.service
> +Wants=first-boot-complete.target
А тут нет противоречия с `Before: first-boot-complete.target`? Может, оно и должно работать, но чёт неочевидно

2022-07-22 07:57 UTC, webconn commented on utils/lib/prepare/wb-prepare.sh
>  wb_prepare_partitions()
Так эта функция ведь теперь тоже не нужна? Хотя она делает mkswap, который у нас при инициализации не делается...

Стоит проверить всё ещё раз на свежем контроллере, прям собрать фит и инициализацию прогнать

2022-07-22 07:57 UTC, webconn commented on debian/wb-utils.wb-prepare.service
> +ConditionFirstBoot=yes
А можешь рассказать заодно, как это внутри устроено? не смотрел?

2022-08-16 16:43 UTC, vdromanov commented on debian/wb-utils.wb-prepare.service
> +ConditionFirstBoot=yes
в телеге обсудили сегодня
вкратце - firstboot определяется по наличию /etc/machine-id

решили убрать его из сборки rootfs ([pr](https://github.com/wirenboard/wirenboard/pull/105))

2022-08-16 16:43 UTC, vdromanov commented on utils/lib/prepare/wb-prepare.sh
>  wb_prepare_partitions()
собрал fit, прогнал инициаллизацию, раскопал интересное вокруг systemd-firstboot и machine-id. починил

2022-08-16 16:45 UTC, vdromanov commented on debian/wb-utils.wb-prepare.service
> +Wants=first-boot-complete.target
кажется, нет
[timesyncd](https://unix.stackexchange.com/questions/507702/before-and-want-for-the-same-systemd-service) также устроен

2022-08-18 13:08 UTC, webconn requested changes

2022-08-18 13:08 UTC, webconn commented on utils/lib/prepare/repart-conditions.sh
> +    exit 1
`1` тут ожидалось? Не `0` надо возвращать, если всё хорошо? (если вообще этот скрипт не убивать)

2022-08-18 13:08 UTC, webconn commented on debian/wb-utils.wb-check-partitions.service
> +ExecCondition=/usr/lib/wb-utils/prepare/repart-conditions.sh
Что-то слишком сложно стало. Даже думаю, не стоит ли вообще этот сервис убрать, потому что без нужных партиций спокойно отвалится всё остальное на этапе монтирования

2022-08-18 13:08 UTC, webconn commented on utils/lib/prepare/wb-prepare.sh
>  wb_prepare_partitions()
А swap нормально создался и подключился?

2022-08-22 11:56 UTC, vdromanov commented on utils/lib/prepare/wb-prepare.sh
>  wb_prepare_partitions()
похоже на то
![2022-08-22_13-23-41](https://user-images.githubusercontent.com/25829054/185899496-f43b1368-5f92-4b7b-aed1-7bd31062ba89.png)

2022-08-24 07:39 UTC, vdromanov commented on utils/lib/prepare/repart-conditions.sh
> +    exit 1
неактуально; убрал вообще весь wb-check-partitions

а так - системда считает 1 невыполнением условия, что-то кроме 1 - ошибкой

2022-08-24 07:39 UTC, vdromanov commented on debian/wb-utils.wb-check-partitions.service
> +ExecCondition=/usr/lib/wb-utils/prepare/repart-conditions.sh
убрал вообще весь wb-check-partitions

2022-08-24 07:50 UTC, vdromanov commented
собрал fit с последними изменениями (без wb-check-partitions) - https://jenkins.wirenboard.com/job/pipelines/job/build-image/1854/

проинициаллизировал wb; погонял factoryreset
как ни странно, всё работает (firstboot - ок; свап тоже есть)

2022-08-24 08:50 UTC, webconn commented on utils/lib/prepare/wb-prepare.sh
>    make-partitions)
Так вот это ведь теперь не нужно (вместе с `wb_prepare_partitions`, может, тоже выпилим нещадно?

2022-08-25 18:17 UTC, evgeny-boger commented on utils/lib/prepare/wb-prepare.sh
> +wb_fix_machine_id()
тут бы написать зачем это вообще надо

2022-08-25 23:07 UTC, vdromanov commented on utils/lib/prepare/wb-prepare.sh
> +wb_fix_machine_id()
готово

2022-08-25 23:07 UTC, vdromanov commented on utils/lib/prepare/wb-prepare.sh
>    make-partitions)
готово

2022-09-06 07:19 UTC, webconn approved these changes

2022-09-08 07:17 UTC, merged