Add GSM modem power management for use with ModemManager on WB7
wirenboard/wb-utils pull request #49
Opened 2022-08-25 05:34 UTC by KraPete

* simple_on/simple_off parameters for wb-gsm to only switch on/off power on SIM A7600E-H/A7602E-H
* should_enable parameter for wb-gsm to check that GSM modem is configured in wb-hwconf-manager

2022-08-25 12:43 UTC, evgeny-boger requested changes

2022-08-25 12:43 UTC, evgeny-boger commented on utils/bin/wb-gsm
> +        echo "USAGE: $0 reset|toggle|on|restart_if_broken|off|set_speed|init_baud|imei|imei_sn|simple_on|simple_off";
названия не очень, лучше конкретнее

2022-08-25 12:43 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    if [[ $gsm_power_type = "1" ]]; then
не обрабатывается else, надо бы с ошибкой хотя бы вылетать, а не что-то делать дальше. Лучше это вообще в самом начале проверить.

2022-08-25 12:43 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +        if of_gpio_is_inverted $(of_prop_required of_get_prop_gpio $OF_GSM_NODE "status-gpios"); then
легаси

2022-08-25 12:43 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    if [[ -n "$gpio_gsm_status" ]]; then
легаси

2022-08-25 12:43 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    sleep 1
мне кажется надо попробовать процедуру "подача питания при pwrkey=1". Это, наверное, сэкономит несколько секунд.

2022-08-25 12:43 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    if [[ -n "$gpio_gsm_status" ]]; then
легаси

2022-08-25 12:43 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    fi
@vdromanov как я понимаю, эта дрянь не включается до конца при зажжённом статусе. И тут надо или sleep добавить, или долбить его AT-командами. Напишешь как сделать?

2022-08-25 12:43 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    sleep 3
почему 3?

2022-08-25 12:43 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    if [[ $gsm_power_type = "2" ]]; then
легаси

2022-08-25 12:43 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    if [[ -n $gpio_gsm_status ]]; then
легаси

2022-08-25 12:43 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +        if of_machine_match "wirenboard,wirenboard-720"; then
посмотри там по DT, кажется лучше проверять вот это старое и ещё wirenboard,wirenboard-7xx

2022-08-25 12:53 UTC, KraPete commented on utils/lib/wb-gsm-common.sh
> +    if [[ $gsm_power_type = "1" ]]; then
Я это скопировал из оригинальной процедуры. Можно ли где-то посмотреть, что этот `power-type` значит? В dtsi 72x прописано = 2. Может, вообще не проверять, здесь же только на WB7 расчитано?

2022-08-25 12:54 UTC, KraPete commented on utils/lib/wb-gsm-common.sh
> +        if of_gpio_is_inverted $(of_prop_required of_get_prop_gpio $OF_GSM_NODE "status-gpios"); then
Можно подробнее, что ты под `легаси` имел ввиду и как хочешь, чтобы было сделано?

2022-08-25 12:57 UTC, KraPete commented on utils/lib/wb-gsm-common.sh
> +    fi
Зачем? Там же usb порты появляются и их MM подхватывает.

2022-08-25 12:59 UTC, KraPete commented on utils/lib/wb-gsm-common.sh
> +    sleep 3
![изображение](https://user-images.githubusercontent.com/86825564/186671118-0f009c94-c052-4a65-a0a2-f961730d76fb.png)

2022-08-25 13:06 UTC, KraPete commented on utils/lib/wb-gsm-common.sh
> +        if of_machine_match "wirenboard,wirenboard-720"; then
Везде, где есть `wirenboard-7xx`, есть и `wirenboard-720`. Но добавлю

2022-08-25 15:11 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    sleep 3
почему не 5.5 тогда?

2022-08-25 15:11 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    sleep 3
ну и это разве не время от импульса до выключения? А у тебя тут длительность импульса.

2022-08-25 15:12 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    fi
во-первых, MM может пометить модем как странный, если будет происходить странное.
во-вторых, клиенты без MM никуда не денутся.

2022-08-25 15:13 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +        if of_gpio_is_inverted $(of_prop_required of_get_prop_gpio $OF_GSM_NODE "status-gpios"); then
я хочу сказать, что поддержки модемов без статуса, с инвертированным статусом. с какими-то другими способами выключения здесь не надо делать. Всё равно не тестируешь, а кода много.

Просто проверять в начале функции, что все эти параметры такие, как ты ожидаешь, если нет - ругаться.

Если будет нужно - будем добавлять поддержку и сразу тестировать.

2022-08-25 15:13 UTC, evgeny-boger commented on utils/lib/wb-gsm-common.sh
> +    if [[ $gsm_power_type = "1" ]]; then
написал ниже

2022-08-25 21:49 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +function simple_gsm_init() {
мб из обычного ``gsm_init()`` вытащить всё, связанное с gpio в какой-нибудь ``gsm_init_gpios()``
и дёргать его здесь и там?

2022-08-25 21:49 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +    if [[ $gsm_power_type = "2" ]]; then
power и pwrkey же дергает
``toggle()``

2022-08-25 21:49 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +    sleep 9
кстати, откуда 9с?

2022-08-25 21:49 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +    fi
да; статус поднимается раньше, чем появляются порты и модем оживает

если здесь надо просто дёрнуть gpio - предлагаю примерную логику: ``toggle()`` -> посмотреть, что за Nс ``get_modem_usb_devices()`` что-то нашел

2022-08-25 21:50 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +function simple_off() {
что-то сложно
кажется, вся эта логика есть в ``switch_off()``

можно из ``switch_off()`` выдернуть в параметры, выключать at-командой или pwrkey'ем
и делать ``unlink_ports()`` где-то снаружи

2022-08-25 21:50 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +function should_enable() {
а концептуально - это зачем вообще?

мб тогда уж имеет смысл - начиная всё с wb6.7 (первый, где модем модулем)

2022-08-25 21:52 UTC, vdromanov requested changes
что-то пока сложновато:(

2022-08-26 05:35 UTC, KraPete commented on utils/lib/wb-gsm-common.sh
> +function should_enable() {
Это для сервиса, который включает модем при старте контроллера (https://github.com/wirenboard/wb-configs/pull/63). Пока договорились всё делать для WB7, WB6 не трогаем.

2022-08-26 05:42 UTC, KraPete commented on utils/lib/wb-gsm-common.sh
> +    sleep 3
В описании же: "Время импульса низкого уровня на PWRKEY для выключения модуля.
![изображение](https://user-images.githubusercontent.com/86825564/186830440-a0a70145-840a-4ada-aaba-8085035bd3fc.png)

2022-08-26 05:48 UTC, KraPete commented
> что-то пока сложновато:(

Вообще задача подразумевает выкинуть всё, что не связано с WB7 и A7600. Так что я специально убрал все ссылки на всякие `toggle` и `gsm_init` и не стал их модифицировать. 
![изображение](https://user-images.githubusercontent.com/86825564/186831049-f442de1a-e4dc-4eec-911d-181b39f04701.png)
https://wirenboard.bitrix24.ru/workgroups/group/218/tasks/task/view/52202/

2022-08-26 05:51 UTC, KraPete commented on utils/lib/wb-gsm-common.sh
> +    sleep 9
https://mt-system.ru/sites/default/files/documents/a7600e-h_hardware_design_v1.02.pdf
![изображение](https://user-images.githubusercontent.com/86825564/186831522-c4384a0a-d324-4701-b2fb-aa6da68292c6.png)

2022-08-26 05:52 UTC, KraPete commented on utils/lib/wb-gsm-common.sh
> +function simple_gsm_init() {
Я внизу написал про то что, была задача вырезать всё только для WB7 и A7600 и не трогать существующий код.

2022-08-26 05:52 UTC, KraPete commented on utils/lib/wb-gsm-common.sh
> +    if [[ $gsm_power_type = "2" ]]; then
Я внизу написал про то что, была задача вырезать всё только для WB7 и A7600 и не трогать существующий код.

2022-08-26 07:09 UTC, KraPete commented on utils/lib/wb-gsm-common.sh
> +    fi
Всё равно не понимаю, чего мы хотим тут добиться? С какой проблемой боремся?
1. Клиенты без MM делают привычный `wb-gsm on` со всей магией.
2. В hw_design китайцы пишут, что usb активируется до поднятия статуса. Но это вообще не важно, т.к. MM работает по событию от udev.
3. Параллельные AT команды + MM - как раз путь в странное поведение. MM не получит нужные ответы. Ели уж используем MM, то он и должен контролировать порт.

2022-09-06 07:27 UTC, webconn requested changes

2022-09-06 07:27 UTC, webconn commented on debian/wb-utils.wb-gsm.service
> +ExecStart=wb-gsm simple_on
Ниже в скриптах это называется `wb7_on` (и `wb7_off` соответственно)

2022-09-14 10:45 UTC, KraPete commented
@vdromanov Посмотри, пожалуйста, ещё раз

2022-09-14 13:21 UTC, webconn approved these changes
С остальными замечаниями ещё нужно разобраться, с моими вроде всё ок

2022-09-15 08:56 UTC, vdromanov approved these changes

2022-09-19 10:36 UTC, merged