Set 127.0.0.1 ip for hostname
wirenboard/wb-utils pull request #64
Opened 2022-11-24 15:13 UTC by ekateluv

https://wirenboard.bitrix24.ru/workgroups/group/218/tasks/task/view/50124/

2022-11-25 06:33 UTC, webconn requested changes
Надо ещё в postinst добавить, чтобы у контроллеров в полях тоже исправилось. Предварительно проверив наличие hostname там, конечно.

2022-11-28 06:00 UTC, webconn requested changes

2022-11-28 06:00 UTC, webconn commented on debian/postinst
> +if [[ $hostname =~ wirenboard-[0-9A-Z]{8} ]]; then
Не, тут нужна проверка, что в `hosts` нет подходящей записи. Ещё можно не стесняться писать в лог, что мы вмешиваемся в системные файлы.

2022-11-28 06:00 UTC, webconn commented on debian/postinst
> +hostname=`cat /etc/hostname`
```suggestion
hostname=$(cat /etc/hostname)
```

2022-11-28 06:00 UTC, webconn commented on debian/postinst
> +
Тут не хватает `#DEBHELPER#`, и ещё `set -e` в начале.
В интернете что-то не нашёл конкретного мануала о том, как в точности правильно писать дебиановские скрипты, но lintian обычно даёт подсказки, когда что-то идёт не так.

2022-11-30 13:33 UTC, webconn requested changes

2022-11-30 13:33 UTC, webconn commented on debian/postinst
> +        hostname_pattern="^[ \\\\t]*127\\\\.0\\\\.0\\\\.1([ \\\\t]+[^ \\\\t]+)*?[ \\\\t]+$hostname[ \\\\t]?.*$"
Ой-ёй. По-моему это уже борщ, достаточно было просто грепом глянуть, что в файле есть упоминание `$hostname`, оно там вряд ли случайно появится. Во всяком случае, точно не штукой с четырьмя бэкслешами перед каждой точкой

2022-11-30 13:37 UTC, ekateluv commented on debian/postinst
> +        hostname_pattern="^[ \\\\t]*127\\\\.0\\\\.0\\\\.1([ \\\\t]+[^ \\\\t]+)*?[ \\\\t]+$hostname[ \\\\t]?.*$"
Это особенность передачи регулярки в авк через строку. Оно там как то два раза проходит, в итоге в момент применения оно сокращается до "\.". Поэтому везде 4 слеша.

2022-11-30 13:58 UTC, ekateluv commented on debian/postinst
> +        hostname_pattern="^[ \\\\t]*127\\\\.0\\\\.0\\\\.1([ \\\\t]+[^ \\\\t]+)*?[ \\\\t]+$hostname[ \\\\t]?.*$"
А если что то типа `wirenboard-XXXXXXXXlsdkfghskldjh`? Засчитается за корректное. Сейчас скрипт отлавливает такие ситуации.

2022-11-30 14:52 UTC, webconn commented on debian/postinst
> +        hostname_pattern="^[ \\\\t]*127\\\\.0\\\\.0\\\\.1([ \\\\t]+[^ \\\\t]+)*?[ \\\\t]+$hostname[ \\\\t]?.*$"
> Это особенность передачи регулярки в авк через строку. Оно там как то два раза проходит, в итоге в момент применения оно сокращается до `\.`. Поэтому везде 4 слеша, потому то они на самом деле в один превращаются.

Ну это ж ни читать, ни писать невозможно.

> А если что то типа `wirenboard-XXXXXXXXlsdkfghskldjh`? Засчитается за корректное. Сейчас скрипт отлавливает такие ситуации.

Хотел бы я взглянуть в глаза тому, кто так написал. Но вообще вот:

```console
$ echo "wirenboard-XXXXXyyyy" | grep "\<wirenboard-XXXXX\>"
$ echo "wirenboard-XXXXX" | grep "\<wirenboard-XXXXX\>"
wirenboard-XXXXX
```

Ну и строго говоря, там может быть адрес не `127.0.0.1`, а любой из этой подсети. Я не вижу смысла это проверять специально, достаточно проверить, что в файле не встречается имя хоста в явном виде.

2022-12-13 15:02 UTC, closed without merging