added usb-otg scripts & misc files
wirenboard/wb-utils pull request #66
Opened 2022-11-28 07:16 UTC by lostpoint-ru

2022-11-28 09:03 UTC, evgeny-boger requested changes
тут надо привязать udev правила только  к WB7, желательно по dt compatible строкам. Можно из самого скрипта конечно

2022-12-02 04:22 UTC, webconn reviewed
Жду причёсанные скрипты только с RNDIS, и чтобы всё это можно было установить на контроллер.

Желательно перед этим что-то сделать с `mass_storage` образом, 64 МБ для него явно избыточны, а для большинства контроллеров это 1/20 от всего места на системном разделе

2022-12-05 14:06 UTC, webconn commented on tests/usb-otg-test-cases.md
> +что второе устройство также получает IP-адрес и имеет доступ к веб-интерфейсу контроллера.
Ещё сюда же:

При повторном подключении провода IP-адрес контроллера в сети RNDIS не меняется.

При отключении и подключении интерфейса в ОС компьютера (со стороны USB host, не проводом, а программно) IP-адрес контроллера в сети RNDIS не меняется.

2022-12-05 14:37 UTC, webconn commented on tests/usb-otg-test-cases.md
> +что второе устройство также получает IP-адрес и имеет доступ к веб-интерфейсу контроллера.
Ещё:

Соединение поднимается, если перезапустить NetworkManager на контроллере

2022-12-16 08:47 UTC, sikmir commented on utils/lib/NetworkManager/system-connections/wb-ecm.nmconnection
> +autoconnect=true
```suggestion
autoconnect=true
read-only=true
```

2022-12-16 08:48 UTC, sikmir commented on utils/lib/NetworkManager/system-connections/wb-rndis.nmconnection
> +autoconnect=true
```suggestion
autoconnect=true
read-only=true
```

2023-01-11 10:03 UTC, sikmir commented on utils/lib/NetworkManager/system-connections/wb-ecm.nmconnection
> +data.read-only=true
```suggestion
wb.read-only=true
```
Переименовали тут https://github.com/wirenboard/wb-nm-helper/pull/30

2023-01-11 10:04 UTC, sikmir commented on utils/lib/NetworkManager/system-connections/wb-rndis.nmconnection
> +data.read-only=true
```suggestion
wb.read-only=true
```

2023-01-11 13:06 UTC, vdromanov commented
неактуально

наработки отсюда + мои причесывания переехали в [другой pr](https://github.com/wirenboard/wb-utils/pull/75)
настройки NM переехали в [wb-configs](https://github.com/wirenboard/wb-configs/pull/88)

2023-01-11 13:06 UTC, closed without merging