Feature/rndis working
wirenboard/wb-utils pull request #75
Opened 2023-01-11 12:58 UTC by vdromanov

причесал [PR Саши](https://github.com/wirenboard/wb-utils/pull/66)

настроечки перетащил в [wb-configs](https://github.com/wirenboard/wb-configs/pull/88)

2023-01-11 13:07 UTC, vdromanov commented
@sikmir про .wb - поправил

2023-01-11 13:08 UTC, webconn requested changes
Ещё надо бинарник от mass storage удалить из репозитория

2023-01-11 13:08 UTC, webconn commented on debian/changelog
> +
Упс

2023-01-11 13:08 UTC, webconn commented on debian/control
> +         nginx-extras, python3-wb-common (>= 2.0.0~~), wb-configs (>= 3.10.0), util-linux,
```suggestion
         nginx-extras, python3-wb-common (>= 2.0.0~~), wb-configs (>= 3.10.0~~), util-linux,
```
Чтобы версия из ветки срабатывала тоже

2023-01-11 13:08 UTC, webconn commented on debian/wb-utils.postinst
> +	deb-systemd-invoke restart NetworkManager || true
Это тут уже не нужно (и весь файл, кажется, тоже)

2023-01-11 13:08 UTC, webconn commented on debian/wb-utils.maintscript
> +rm_conffile /etc/init.d/wb-usb-otg 3.0.0~
Не нужно

2023-01-11 13:08 UTC, webconn commented on utils/lib/wb-usb-otg/wb-usb-otg-common.sh
> +N="usb0"
Плохое название для переменной

2023-01-11 13:08 UTC, webconn commented on utils/lib/wb-usb-otg/wb-usb-otg-common.sh
> +g=/sys/kernel/config/usb_gadget/g1
Тоже непонятно

2023-01-11 13:08 UTC, webconn commented on utils/lib/wb-usb-otg/wb-usb-otg-common.sh
> +}
А мы не хотим выкинуть, чтобы не дразниться?

2023-01-11 13:08 UTC, webconn commented on utils/lib/wb-usb-otg/wb-usb-otg-common.sh
> +    if [ "$1" == "ecm" ]; then
На ровном месте `if` получился, предлагаю убрать вообще `ecm`

2023-01-11 13:41 UTC, webconn requested changes

2023-01-11 13:41 UTC, webconn commented on mass-storage-image/create-image.sh
> +apt-get install dosfstools
Так нельзя, надо в build-depends вписать пакет

2023-01-11 13:41 UTC, webconn commented on mass-storage-image/create-image.sh
> +#!/bin/bash
Весь этот скрипт в принципе не выполняется при сборке пакета, а надо бы

2023-01-12 15:35 UTC, vdromanov commented on debian/changelog
> +
поправил

2023-01-12 15:35 UTC, vdromanov commented on debian/control
> +         nginx-extras, python3-wb-common (>= 2.0.0~~), wb-configs (>= 3.10.0), util-linux,
готово

2023-01-12 15:35 UTC, vdromanov commented on debian/wb-utils.postinst
> +	deb-systemd-invoke restart NetworkManager || true
готово

2023-01-12 15:35 UTC, vdromanov commented on debian/wb-utils.maintscript
> +rm_conffile /etc/init.d/wb-usb-otg 3.0.0~
готово

2023-01-12 15:35 UTC, vdromanov commented on utils/lib/wb-usb-otg/wb-usb-otg-common.sh
> +N="usb0"
готово

2023-01-12 15:35 UTC, vdromanov commented on utils/lib/wb-usb-otg/wb-usb-otg-common.sh
> +g=/sys/kernel/config/usb_gadget/g1
готово

2023-01-12 15:35 UTC, vdromanov commented on utils/lib/wb-usb-otg/wb-usb-otg-common.sh
> +}
готово + в wb-configs убрал ecm

2023-01-12 15:35 UTC, vdromanov commented on utils/lib/wb-usb-otg/wb-usb-otg-common.sh
> +    if [ "$1" == "ecm" ]; then
готово

2023-01-12 15:35 UTC, vdromanov commented on mass-storage-image/create-image.sh
> +apt-get install dosfstools
готово

2023-01-12 15:36 UTC, vdromanov commented on mass-storage-image/create-image.sh
> +#!/bin/bash
теперь image собирается при сборке пакета
+ переделал сборку image, чтобы не был нужен рут

2023-01-13 07:28 UTC, webconn requested changes

2023-01-13 07:28 UTC, webconn commented on mass-storage-image/create-image.sh
> +losetup -d /dev/loop0
```suggestion
lo_device=$(losetup -f)
losetup -o$offset "$lo_device" ./mass_storage

mkdosfs "$lo_device"

mkdir -p /mnt/ms-test

mount -t vfat "$lo_device" /mnt/ms-test

cp ./contents/* /mnt/ms-test

ls -l /mnt/ms-test

umount /mnt/ms-test
losetup -d "$lo_device"
```

А то у кого-то loop0 бывает занят

2023-01-13 07:28 UTC, webconn commented on Makefile
> +	install -m 0755 -d $(BINDIR) $(LIBDIR) $(PREPARE_LIBDIR) $(IMAGEUPDATE_POSTINST_DIR) $(USBOTGDIR)
Тут специально избавлялись от этой строчки, добавляя к следующим `install` ключ `-D`, думаю, тут тоже можно

2023-01-13 07:28 UTC, webconn commented on Makefile
> +	utils/lib/wb-usb-otg/create-mass-storage-image.sh
Этот скрипт я бы вытащил из `utils`, раз он потом в пакет не добавляется, чтобы путаницы не возникало

2023-01-13 07:28 UTC, webconn commented on utils/lib/wb-usb-otg/create-mass-storage-image.sh
> +IMAGE_FNAME="utils/lib/wb-usb-otg/mass_storage.img"
А можно было бы это и `CONTENTS_DIR` в аргументы положить и вызывать потом ручками (не обязательно переделывать сейчас).

А чем решение через loop было плохо / чем это лучше?

2023-01-13 07:28 UTC, webconn commented on utils/lib/wb-usb-otg/create-mass-storage-image.sh
> +BS_K="512K"
Если сделать тут просто `512`, образ станет на порядок меньше размером, при этом всё продолжает работать (проверил на Linux и Win7)

2023-01-13 07:47 UTC, webconn commented on tests/usb-otg-test-cases.md
> +1. Берем компьютер/ноутбук с установленной Windows 8/10/11, подключаем кабелем usb-c<>usb-c
Допиши сюда и ниже про Windows 7, концептуально оно работает (драйверов в Windows 7 хватает для всего). И можно дописать, что если устройство не определяется (что в Linux, что в Windows), то надо попробовать подключить контроллер через USB-хаб, желательно 2.0

2023-01-13 07:47 UTC, webconn commented on utils/lib/wb-usb-otg/create-mass-storage-image.sh
> +IMAGE_FNAME="utils/lib/wb-usb-otg/mass_storage.img"
Поковырялся, в принципе через `mtools` и правда удобней специфические вещи делать (например, атрибуты файлам раздавать)

2023-01-13 08:02 UTC, sikmir commented on Makefile
> +LIBDIR = $(DESTDIR)/$(prefix)/lib/wb-utils
```suggestion
BINDIR = $(DESTDIR)$(prefix)/bin
LIBDIR = $(DESTDIR)$(prefix)/lib/wb-utils
```

2023-01-13 10:09 UTC, vdromanov commented on Makefile
> +LIBDIR = $(DESTDIR)/$(prefix)/lib/wb-utils
готово

2023-01-13 10:09 UTC, vdromanov commented on tests/usb-otg-test-cases.md
> +1. Берем компьютер/ноутбук с установленной Windows 8/10/11, подключаем кабелем usb-c<>usb-c
готово

2023-01-13 10:09 UTC, vdromanov commented on utils/lib/wb-usb-otg/create-mass-storage-image.sh
> +BS_K="512K"
готово

2023-01-13 10:09 UTC, vdromanov commented on utils/lib/wb-usb-otg/create-mass-storage-image.sh
> +IMAGE_FNAME="utils/lib/wb-usb-otg/mass_storage.img"
сделал аргументы скрипту-сборщику

2023-01-13 10:09 UTC, vdromanov commented on Makefile
> +	utils/lib/wb-usb-otg/create-mass-storage-image.sh
готово

2023-01-13 10:09 UTC, vdromanov commented on Makefile
> +	install -m 0755 -d $(BINDIR) $(LIBDIR) $(PREPARE_LIBDIR) $(IMAGEUPDATE_POSTINST_DIR) $(USBOTGDIR)
готово

2023-01-15 09:49 UTC, evgeny-boger commented on utils/lib/wb-usb-otg/wb-usb-otg-common.sh
> +    echo "1a:55:89:a2:69:44" > ${USBGADGET_CONFIG}/functions/rndis.$USBDEV/host_addr
написать бы, откуда взяты эти маки

2023-01-15 18:15 UTC, evgeny-boger commented on utils/lib/wb-usb-otg/wb-usb-otg-start.sh
> +trap "remove_usb_gadget; exit 1" ERR
тут ошибка: remove_usb_gadget недостаточно без config_reset.
Ну и надо на это тест какой-нибудь написать, хотя бы текстом для человека.

2023-01-16 10:01 UTC, webconn approved these changes
Комментарии от Жени надо поправить, в остальном вроде ок

2023-01-17 12:01 UTC, webconn requested changes
Опять откуда-то всплыл старый образ mass_storage на 64 МБ в репозитории

2023-01-17 22:41 UTC, vdromanov commented
доделок-лист с последнего демо:
![2023-01-18_01-29-41](https://user-images.githubusercontent.com/25829054/213027886-18421da8-879e-4ea7-a5f1-06aee4811ab4.png)

по п.4 была проблема: плохо работало на убунте с NM (ноут не получал адрес); причина - разные mac при каждом подключении wb => пулл адресов (1) переполнялся старыми leases. Решили dispatcher-скриптом на wb

2023-01-18 05:22 UTC, sikmir commented on Makefile
> +	build_scripts/create-mass-storage-image.sh utils/lib/wb-usb-otg/mass_storage_contents/ build_scripts/mass_storage.img
Лучше бы создание образа в отдельный make таргет, а в `make install` только установки оставить.

2023-01-18 05:39 UTC, sikmir commented on Makefile
> +	rm -f build_scripts/mass_storage.img
Еще в `.gitignore` надо добавить.

2023-01-18 05:54 UTC, sikmir commented on build_scripts/create-mass-storage-image.sh
> +size=$(du --block-size=$BS -s "$CONTENTS_DIR" | awk '{print $1}')
```suggestion
size=$(du -B $BS -s "$CONTENTS_DIR" | cut -f1)
```
BSD `du` (на macOS) не умеет в длинную опцию `--block-size`.

2023-01-18 06:19 UTC, sikmir commented on utils/lib/wb-usb-otg/mass_storage_contents/webui.html
> +        If you are not redirected automatically, follow this <a href='http://10.200.200.1'>link to access WB webui</a>.
Может чтобы не повторять IP 4 раза сделать шаблоном? Например:
```sh
cat utils/lib/wb-usb-otg/mass_storage_contents/webui.html.jinja
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="refresh" content="0; url={{ address }}">
        <script type="text/javascript">
            window.location.href = "{{ address }}"
        </script>
        <title>WB webui</title>
    </head>
    <body>
        If you are not redirected automatically, follow this <a href='{{ address }}'>link to access WB webui</a>.
    </body>
</html>
$ cat utils/lib/wb-usb-otg/mass_storage_contents/README.txt.jinja
Controller address is {{ address }}
```
И в Makefile:
```
export address=http://10.200.200.1
j2 -o utils/lib/wb-usb-otg/mass_storage_contents/webui.html utils/lib/wb-usb-otg/mass_storage_contents/webui.html.jinja
j2 -o utils/lib/wb-usb-otg/mass_storage_contents/README.txt utils/lib/wb-usb-otg/mass_storage_contents/README.txt.jinja
```

2023-01-18 11:16 UTC, webconn approved these changes
Мне всё нравится, правь замечания от @sikmir и давай вливать

2023-01-18 14:19 UTC, vdromanov commented on utils/lib/wb-usb-otg/mass_storage_contents/webui.html
> +        If you are not redirected automatically, follow this <a href='http://10.200.200.1'>link to access WB webui</a>.
готово

2023-01-18 14:19 UTC, vdromanov commented on build_scripts/create-mass-storage-image.sh
> +size=$(du --block-size=$BS -s "$CONTENTS_DIR" | awk '{print $1}')
готово

2023-01-18 14:19 UTC, vdromanov commented on Makefile
> +	rm -f build_scripts/mass_storage.img
готово

2023-01-18 14:19 UTC, vdromanov commented on Makefile
> +	build_scripts/create-mass-storage-image.sh utils/lib/wb-usb-otg/mass_storage_contents/ build_scripts/mass_storage.img
готово

2023-01-18 14:37 UTC, vdromanov commented on utils/lib/wb-usb-otg/wb-usb-otg-start.sh
> +trap "remove_usb_gadget; exit 1" ERR
готово

2023-01-18 14:46 UTC, sikmir approved these changes

2023-01-18 17:42 UTC, merged