Feature/57342 mm compatibility
wirenboard/wb-utils pull request #79
Opened 2023-01-27 07:55 UTC by vdromanov

надо поломать wb-gsm для модемов, поддерживаемых в MM (wbc-4g)

- wb-gsm.service (включающий питание модему) теперь запускается не только на wb7
- аккуратно влез в логику wb-gsm; вроде получилось

гонял на столе, включая/отключая игнорирование модемов через udev; на реальных железках еще не гонял

основная сложность - модем должен быть включен для того, чтобы MM его видел => в сценарии "модем поддерживается в MM; выключен; включаем через wb-gsm on" модем может включиться. Проблемой это не считаю, т.к. в случае поддержки в MM, питание модема рулится wb-gsm.service

2023-01-30 07:11 UTC, webconn commented on utils/lib/wb-gsm-common.sh
> +    check_is_not_driven_by_mm
Мне кажется, это должно быть до `init_usb_connection` выше? Ведь `init_usb_connection` залезает в порты и пишет туда AT

2023-01-30 07:12 UTC, webconn commented
А ещё я хочу тесткейсы, на которых можно проверить это поведение

2023-01-30 11:55 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +    check_is_not_driven_by_mm
всё верно

здесь проблема: чтобы MM увидел модем, он должен быть включен
=> задумка была, чтобы MM увидел модем, пока wb-gsm его включает/щупает/делает другую магию

задумка работает плохо => сделал, как ты предлагаешь

timeouts не хочу, т.к. вокруг wb-gsm всё очень хрупко => у клиентов вполне может быть что-то завязано на время работы wb-gsm
=> на случай "модем работает через MM => выключен => включаем через wb-gsm on => включился (а должен заругаться)" - предлагаю забить, т.к. он возможен только в синтетических сценариях (на реальном WB, модем, поддерживаемый в MM, включен уже со старта через wb-gsm.service)
расписал в тесткейсах

(udevadm trigger - тоже не помог)

2023-01-31 06:12 UTC, webconn requested changes

2023-01-31 06:12 UTC, webconn commented on tests/wb-gsm-modemmanager-test-cases.md
> +Выполнить ``wb-gsm should_enable; echo $?`` Должно выполниться успешно (rc=0).
```suggestion
Выполнить `wb-gsm should_enable; echo $?` Должно выполниться успешно (rc=0).
```
здесь и во всём файле

https://www.markdownguide.org/basic-syntax/#code

2023-01-31 06:12 UTC, webconn commented on tests/wb-gsm-modemmanager-test-cases.md
> +1)  Взять wbc-4g (поддерживается в MM); выставить его в webui.
выставить == настроить в hwconf?

2023-01-31 06:12 UTC, webconn commented on utils/lib/wb-gsm-common.sh
> +        if is_model "a7600x"; then
Может, через udev смотреть, стоит ли на модеме unmanaged? Чтобы источник правды был один и потом не пришлось всё переделывать

2023-01-31 06:12 UTC, webconn commented on utils/lib/wb-gsm-common.sh
> +    fi
Я тут ещё раз посмотрел на всё это и подумал, что это скользкое место. То есть, как только modemmanager по какой-то причине будет неактивен (перезапускается или упал), все скрипты внезапно обретут власть над модемом.

Мы вроде уже решили, что ModemManager у нас будет идти по умолчанию, так зачем это всё тогда? нам не надо просто по умолчанию гасить любую активность здесь? (Ну или, например, сделать какой-нибудь файл-флаг в системе, который запретит запускаться MM и одновременно с этим разрешит wb-gsm, чтобы люди могли откатиться на свои старые скрипты перманентно)

Или вообще ориентироваться только на MM_UNMANAGED в udev, так будет супер-аккуратно и источник правды о том, кто должен управлять модемом, будет ровно один

2023-01-31 06:13 UTC, webconn commented
Если хочешь, давай вместе синхронно обсудим изменения, чтобы не играть дальше в пинг-понг ревью

2023-01-31 12:19 UTC, vdromanov commented on tests/wb-gsm-modemmanager-test-cases.md
> +1)  Взять wbc-4g (поддерживается в MM); выставить его в webui.
да; расписал чуть по-другому

2023-01-31 12:19 UTC, vdromanov commented on tests/wb-gsm-modemmanager-test-cases.md
> +Выполнить ``wb-gsm should_enable; echo $?`` Должно выполниться успешно (rc=0).
готово

2023-01-31 12:19 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +        if is_model "a7600x"; then
здесь модем еще выключен => кажется, udev - бесполезен

2023-01-31 12:19 UTC, vdromanov commented on utils/lib/wb-gsm-common.sh
> +    fi
переделал на udev (последний абзац)
работает - также

2023-01-31 12:27 UTC, webconn approved these changes, later dismissed
Связанный PR: https://github.com/wirenboard/wb-configs/pull/91

Выглядит хорошо, я бы попросил ещё кого-нибудь побыть тестировщиком

2023-01-31 12:27 UTC, webconn commented on utils/lib/wb-gsm-common.sh
> +        if is_model "a7600x"; then
Справедливо

2023-02-01 07:29 UTC, webconn commented on tests/wb-gsm-modemmanager-test-cases.md
> +*   wb-configs >= 3.10.3 (с правилами udev по игнорированию модемов)
А почему в debian/control нет этой зависимости?

2023-02-01 08:05 UTC, vdromanov commented on tests/wb-gsm-modemmanager-test-cases.md
> +*   wb-configs >= 3.10.3 (с правилами udev по игнорированию модемов)
ну зависимость не выглядит нужной (работает-то всё и со старым wb-configs) + всё в одном релизе


прописал явно

2023-02-01 18:46 UTC, webconn approved these changes

2023-02-02 07:42 UTC, merged